openapi: 3.0.1
info:
  title: Auth Service API
  version: 1.0.0
  description: APIs for authentication and authorization (JWT, login, logout).

paths:
  /auth/register:
    post:
      summary: Register a new user
      operationId: register
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        '200':
          description: User registered successfully

  /auth/login:
    post:
      summary: Login and receive JWT
      operationId: login
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: JWT token response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /auth/refresh:
    post:
      summary: Refresh JWT token
      operationId: refreshToken
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: New JWT token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'

  /auth/logout:
    post:
      summary: Logout user
      operationId: logout
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LogoutRequest'
      responses:
        '200':
          description: Logged out successfully

components:
  schemas:
    RegisterRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        role:
          type: string
          enum: [PATIENT, THERAPIST, ADMIN]

    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
        expiresIn:
          type: integer

    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string

    LogoutRequest:
      type: object
      properties:
        refreshToken:
          type: string
